version: "3"
services:
  rasa:
    build: rasa_ai
    container_name: rasa_server
    user: root
    ports:
      - "5005:5005"
    healthcheck:
      test: curl --fail -s http://localhost:5005/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - actions
  actions:
    build: rasa_ai/actions
    container_name: rasa_actions_server
    ports:
      - "5055:5055"
    environment:
      - TRANSFORMERS_CACHE=/app/cache
    volumes:
      - ./rasa_ai/actions:/app/actions
  server:
    build: ./server
    container_name: fastapi_server
    command: uvicorn main:app --host 0.0.0.0 --log-level debug
    ports:
      - "8000:8000"
    environment:
      - RASA_HOST=rasa
    depends_on:
      - rasa