version: "3"
services:
  actions:
    build: rasa_ai/actions
    container_name: rasa_actions_server
    ports:
      - "5055:5055"
    environment:
      - TRANSFORMERS_CACHE=/app/cache
    volumes:
      - ./rasa_ai/actions:/app/actions
